### ISSUE TITLE
ID err

### ISSUE THREAD

**Issue by maxusaurelius** [jzobac/WH5029#1]
192 : b: 972 484 4904 0 0 0 0 0 
t: 1010101010100101100110000010111000000000111111110011000000000000000000000000101100011101

CRC: 6F
crc_low_bits: F
CRC 0x6F OK

# bity: 152
Validace typu OK

# bity: 0
Validace two complement OK
crc: 
id: 
ID nesedi! Koncim.
---------------------------

obcas prolozeno chybou:

192 : b: 972 484 4880 0 0 0 0 0 
t: 1010101010100101100110000010111000000001000000000011000000000000000000000000101111010011

CRC: 5F
crc_low_bits: F
CRC 0x5F OK

# bity: 152
Validace typu OK

# bity: 1
Err validace two complement
Nesedi two complement! Koncim

**Comment by jzobac** [comment]
Cau,
kdyz nesedi doplnek teploty, tak nema smysl dal pokracovat, teplota je vadna, mam v hlave par napadu, ktere by to mohly teoreticky opravit a nejake procento zprav zrekonstruovat, jestli na to bude chvilka, tak si s tim pohraju. Je dobre znameni ze nejsem sam komu to zlobi, hold cina :)

zamen radek:
const byte const_id = 255;

za
const byte const_id = 46;


a zacne to fungosat, jakmile venkovni jednotku vyresetujes, tak je poreba zmenit toto ID (napisu do "manualu"´), v tom kodu je to bit 25 - 32

```
101010101010010110011000 00101110 00000000111111110011000000000000000000000000101100011101
```
Jirka
