### ISSUE TITLE
Adding DHT = Exception

### ISSUE THREAD

**Issue by ronnicek** [jzobac/WH5029#2]
Hi,

first of all thanks for great code! I'm trying to add DHT sensor to RXB6 so I can have also "indoor" temperature and humidity :)

But when I add my function dhtcheck(); right below dprintln(CRC); I got time to time Expection.. but I have no idea why.. :-/ (it's enought to add delay(1000); right under CRC output and I get Expection every time.

My code looks like this:

```void dhtcheck() {
  int WiFiStrength = 0;
  char celsiusTemp[7];
  char humidityTemp[7];
  WiFiStrength = WiFi.RSSI();
  float dhthumid = dht.readHumidity();
  float dhttemp = dht.readTemperature();

  if (isnan(dhthumid) || isnan(dhttemp)) {
    dprint(F("Failed to read from DHT sensor!"));
    strcpy(celsiusTemp, "Failed");
    strcpy(humidityTemp, "Failed");
  } else {

    float thcal = dht.computeHeatIndex(dhttemp, dhthumid, false);
    dtostrf(dhttemp, 2, 1, celsiusTemp);
    dtostrf(dhthumid, 2, 1, humidityTemp);

    dprint(F("Temperature: "));
    dprintln(celsiusTemp);
    dprint(F("Humidity: "));
    dprintln(humidityTemp);
    dprint(F("WiFi Strength: "));
    dprintln(WiFiStrength);
  }
}
```

Exception looks like this:
```Exception (0):
epc1=0x40204c38 epc2=0x00000000 epc3=0x00000000 excvaddr=0x00000000 depc=0x00000000

ctx: sys 
sp: 3ffffc30 end: 3fffffb0 offset: 01a0

>>>stack>>>
3ffffdd0:  4010719c 00000030 0000001f ffffffff  
3ffffde0:  ffffffff 00000020 00000000 00000000  
3ffffdf0:  fff00fff 60009a00 60000200 00000022  
3ffffe00:  3fffc200 40107164 3fffc258 4000050c  
3ffffe10:  40004378 00000030 00000016 ffffffff  
3ffffe20:  60000200 00000008 00000000 80000000  
3ffffe30:  20000000 3fff1390 80000000 203fc060  
3ffffe40:  80000000 3fffc6fc 00000001 3fff1394  
3ffffe50:  00000294 003fc060 60000600 00000030  
3ffffe60:  40107200 3ffec920 3ffe9da4 40204c44  
3ffffe70:  40107200 00000020 00000022 401071ea  
3ffffe80:  ffffffff 00000020 4000050c 00000022  
3ffffe90:  3fffc200 40107164 3fffc258 00000022  
3ffffea0:  3fffc200 40107164 3fffc258 4000050c  
3ffffeb0:  40000f83 00000030 0000001e ffffffff  
3ffffec0:  40000f3d 00000023 00000000 3fffd9d0  
3ffffed0:  00000000 00000000 00000000 fffffffe  
3ffffee0:  ffffffff 3fffc6fc 00000001 3fffdab0  
3ffffef0:  00000000 3fffdad0 3ffef2a0 00000030  
3fffff00:  00000000 400042db 0000007d 60000600  
3fffff10:  40004b31 3fff1334 000002f4 003fc000  
3fffff20:  40105fe2 3ffee090 3ffed130 4010763c  
3fffff30:  4020c961 3ffed130 3ffee090 02e7f7ca  
3fffff40:  3fff1334 00001000 4020cdf6 00000008  
3fffff50:  00000000 00000000 4020cea3 3ffed1e4  
3fffff60:  3ffee090 00e85ba1 3ffee090 40201344  
3fffff70:  4021e579 3ffed1e4 3ffee090 02e7c92a  
3fffff80:  4021e5be 3fffdab0 00000000 3fffdcb0  
3fffff90:  3ffee0b0 3fffdad0 3ffef2a0 40205803  
3fffffa0:  40000f49 000181f7 3fffdab0 40000f49  
<<<stack<<<

 ets Jan  8 2013,rst cause:2, boot mode:(3,6)

load 0x4010f000, len 1384, room 16 
tail 8
chksum 0x2d
csum 0x2d
v3ffe8798
~ld
⸮
```

Any idea what it can be and why?

By the way.. I added to your code also calculation of dewpoint and feeltemperature, should I send you a pull request? :)

// J

**Comment by jzobac** [comment]
Hi,
it crashed probably on interrupts. I don't use stopping of rfcontrol, because on my code it is not needed, but when you use some wifi functions (delay too; get rssi, etc), it will crash -> ESP8266 hw limitations (hope ESP32 will be much more bullet proof / user friendly).

Try this
RFControl::stopReceiving();
  int WiFiStrength = 0;
  char celsiusTemp[7];
  char humidityTemp[7];
  WiFiStrength = WiFi.RSSI();
  float dhthumid = dht.readHumidity();
  float dhttemp = dht.readTemperature();

  if (isnan(dhthumid) || isnan(dhttemp)) {
    dprint(F("Failed to read from DHT sensor!"));
    strcpy(celsiusTemp, "Failed");
    strcpy(humidityTemp, "Failed");
  } else {

    float thcal = dht.computeHeatIndex(dhttemp, dhthumid, false);
    dtostrf(dhttemp, 2, 1, celsiusTemp);
    dtostrf(dhthumid, 2, 1, humidityTemp);

    dprint(F("Temperature: "));
    dprintln(celsiusTemp);
    dprint(F("Humidity: "));
    dprintln(humidityTemp);
    dprint(F("WiFi Strength: "));
    dprintln(WiFiStrength);
  }
  RFControl::startReceiving(0);
  //RFControl::startReceiving(D2);  //ESP8266
}

If it will work, I will correct the code to prevent exceptions.


I have no problem to add new functions, but they must be compatible with  CC BY-NC-SA 4.0 licence.

Radius

**Comment by ronnicek** [comment]
Thanks! I will try that. I found functions on internet and just rewrite them to C (with my bad C skills). I will share them during next week :)

I will close this issue for now.
